name: Build Android Release APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Code ophalen
      uses: actions/checkout@v4

    - name: Java instellen
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Setup Gradle zonder dat de gradlew wrapper in je repo hoeft te staan
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: APK Builden (Release)
      run: gradle assembleRelease

    - name: Release APK Opslaan als Download
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/build/outputs/apk/release/
