name: Build Android Release APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Code ophalen
      uses: actions/checkout@v4

    - name: Java instellen via DPZXJAVAFIX (door Devon, ook wel DPZX)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    # We vertellen Gradle om de release-build te ondertekenen met de debug-key
    - name: APK Builden (Release) (dit word met debug gedaan..)
      run: |
        cd app
        gradle assembleRelease -Pandroid.injected.signing.config.file=debug.keystore

    - name: Release APK Opslaan als Download
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: app/app/build/outputs/apk/release/
